### ISSUE TITLE
cross-device link not permitted error when launching

### ISSUE THREAD

**Issue by Xananax** [superpowers/superpowers-app#52]
Running the app from the itch.io launcher gives me:

```
Uncaught Exception:
Error: EXDEV: cross-device link not permitted, rename '/home/xananax/.local/share/Superpowers' -> '/hawm/.back/.config/Superpowers'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at Object.getPaths [as default] (/hawm/.back/.config/itch/apps/Superpowers/superpowers-v2.0.0-linux-x64/resources/app/getPaths.js:49:16)
    at EventEmitter.onAppReady (/hawm/.back/.config/itch/apps/Superpowers/superpowers-v2.0.0-linux-x64/resources/app/main.js:52:23)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
```

Here's the complete [debug log created by itch.io](https://gist.github.com/b2596293344962f7fcbaf4fbb327db7c).

Both '/' and '/hawm' are EXT4 drives, but they are two different (physical) drives, I suppose that's where the error comes from.  
My `~/.config` lives in my second `hawm` drive, and is symlinked, because my main gets filled up fast.

Running superpowers from the command line produces the same error. Additionally, I get the following output:

```
/hawm/.back/.config/Superpowers
Migrating data from /home/xananax/.local/share/Superpowers to /hawm/.back/.config/Superpowers...
```

To note, I have no `.local/share/Superpowers` directory, nor a `.back/.config/Superpowers` directory. I have a `/hawm/.back/.config/superpowers-app/` directory, which contains 3 symlinks, two of which are broken (`SingletonCookie` and `SingletonLock`)

I'm on Arch Linux.

[Cross reference issue on itch](https://github.com/itchio/itch-compatibility-watchlist/issues/180)

**Comment by Xananax** [comment]
Also to note, I've ran superpowers in the past, on the same machine with the same OS; ~~not the same format though~~, and it was when Superpowers was just out. But it worked without a problem.  
Edit: Found that I still had the install; it was version 0.19, and still works without a problem

Also, I've tried:
- downloading the build from my browser and unzipping to a custom directory
- installing through my package manager (package [here](https://aur.archlinux.org/packages/superpowers/))

I get the same cross-device error in both cases.

**Comment by elisee** [comment]
Hi! Thanks for the report.

No idea what could be the cause. Anybody on Linux with some idea of what's happening?
